#Localization file with English.

thispath = 'You are on this path:'
Jump_func_text = '1) Move to previous directory \n2) Move to next directory \n'
Directory_text = 'Enter directory name: '
function_text = 'File-Manager made by RIDERIUS \nVersion 0.3.0 \n1) View all files \n2) Move between directories \n3) Copy \n4) Move \n5) Change \n6) Delete \n7) Close \n'
Copy_func_text = '1) Copy files \n2) Copy directory \n'
file_text = 'Enter file name: '
CaMO = 'Copy to this directory? (y/n) '
CaMO_text2 = 'Move to this directory? (y/n) '
Move_func_text = '1) Move file \n2) Move directory \n'
name_text = 'Enter the name of the renamed file with the format: '
Remove_func_text = '1) Deleting files \n2) Deleting directories \n'
REFI_func_text = '1) Permanently deleting files \n2) Deleting files through the trash can \n'
REDIR_func_text = '1) Permanently deleting directories \n2) Deleting directories via the trash can \n'